import { lazy } from "react"

export const ROUTES = [
  {
    path: "/access-code",
    title: "Home",
    main: lazy(() => import("new_pages/access-code")),
    authRequired: false,
  },
  {
    path: "/profile/:address",
    title: "Profile",
    main: lazy(() => import("new_pages/profile")),
    authRequired: false,
  },
  {
    path: "/edit/profile",
    title: "Edit Profile",
    main: lazy(() => import("new_pages/edit-profile")),
    authRequired: false,
  },
  {
    path: "/sell",
    title: "Sell NFT",
    main: lazy(() => import("new_pages/sell")),
    authRequired: false,
  },
  {
    path: "/newBuy",
    title: "Buy NFT",
    main: lazy(() => import("new_pages/buy")),
    authRequired: false,
  },
  {
    path: "/nft/detail/:asset",
    title: "NFT Detail",
    main: lazy(() => import("new_pages/detail")),
    authRequired: false,
  },
  {
    path: "/trending",
    title: "Trending",
    main: lazy(() => import("new_pages/trending")),
    authRequired: false,
  },
  {
    path: "/collection/:contractAddress",
    title: "Collection",
    main: lazy(() => import("new_pages/collection")),
    authRequired: false,
  },
  // {
  //   path: "/mint",
  //   title: "Mint",
  //   main: lazy(() => import("new_pages/mint")),
  //   authRequired: false,
  // },
  {
    path: "/nftnize",
    title: "Create NFT",
    main: lazy(() => import("new_pages/mint")),
    authRequired: true,
  },

  {
    path: "/explore",
    title: "Explore",
    main: lazy(() => import("new_pages/explore")),
    authRequired: false,
  },
  {
    path: "/landing",
    title: "Home",
    main: lazy(() => import("new_pages/home")),
    authRequired: true,
  },
  {
    path: "/",
    title: "Home",
    main: lazy(() => import("new_pages/landing")),
    authRequired: false,
  },
  {
    path: "/mint-nft/:index",
    title: "Minted NFT Details",
    main: lazy(() => import("new_pages/nft-viewer")),
    authRequired: false,
  },
  {
    path: "/nft/:index",
    title: "NFT Details",
    main: lazy(() => import("new_pages/nft-details")),
    authRequired: true,
  },
  // {
  //   path: "/nftnize",
  //   title: "Create NFT",
  //   main: lazy(() => import("new_pages/create-nft")),
  //   authRequired: true,
  // },
  // {
  //   path: "/mint",
  //   title: "Create NFT",
  //   main: lazy(() => import("new_pages/create-nft")),
  //   authRequired: true,
  // },
  {
    path: "/markets",
    title: "Market Collections",
    main: lazy(() => import("new_pages/explore-collection")),
    authRequired: true,
  },
  {
    path: "/markets/:id",
    title: "Collection Details",
    main: lazy(() => import("new_pages/explore-collection-details")),
    authRequired: true,
  },
  {
    path: "/buy",
    title: "Buy NFTs",
    main: lazy(() => import("new_pages/exploreBuy")),
    authRequired: true,
  },
  {
    path: "/buy/:asset",
    title: "Application",
    main: lazy(() => import("new_pages/buy")),
    authRequired: true,
  },
  {
    path: "/sell/:id?",
    title: "Sell NFT",
    main: lazy(() => import("new_pages/create-application")),
    authRequired: true,
  },
  {
    path: "/creators/:address",
    title: "Creators",
    main: lazy(() => import("new_pages/creator-details")),
    authRequired: true,
  },
  {
    path: "/faq",
    title: "FAQ",
    main: lazy(() => import("new_pages/faq")),
    authRequired: true,
  },
  {
    path: "/tutorial",
    title: "Tutorial",
    main: lazy(() => import("new_pages/tutorial")),
    authRequired: true,
  },
  {
    path: "/terms-of-service",
    title: "Terms & Conditions",
    main: lazy(() => import("new_pages/terms-conditions")),
    authRequired: true,
  },
  {
    path: "/privacy-policy",
    title: "Privacy Policy",
    main: lazy(() => import("new_pages/privacy-policy")),
    authRequired: true,
  },
  // {
  //   path: "*",
  //   title: "Not Found",
  //   main: lazy(() => import("new_pages/not-found-page")),
  //   authRequired: true,
  // },
  {
    path: "*",
    title: "Not Found",
    main: lazy(() => import("new_pages/404")),
    authRequired: false,
  },
  // {
  //   path: "*",
  //   title: "Coming Soon",
  //   main: lazy(() => import("new_pages/coming-soon")),
  //   authRequired: true,
  // },
]
